version: "3.8"
services:
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234Qwer!

  app:
    build:
      context: .
    ports:
      - 3000:3000
    links:
      - db
    environment:
      POSTGRES_HOST: db

volumes:
  db_data:
